In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [2]:
import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

True
Tesla T4


In [3]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avalilable.Using CPU")

GPU is available!
Using GPU: Tesla T4


In [4]:
#Creating a Tensor

In [6]:
#using empty
a=torch.empty(2,3)
a

tensor([[3.1505e+01, 0.0000e+00, 3.1011e+01],
        [0.0000e+00, 0.0000e+00, 1.3873e-43]])

In [7]:
#check type
type(a)

torch.Tensor

In [8]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#use of seed
torch.rand(2,3)

tensor([[0.4757, 0.6180, 0.4253],
        [0.1298, 0.0660, 0.3628]])

In [11]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
#other ways
#arange
print("using arange ->",torch.arange(0,10,2))

#using linspace
print("using linspace ->",torch.linspace(0,10,10))

#using eye
print("using eye ->",torch.eye(5))

#using full
print("using full ->",torch.full((3,3),5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [15]:
#Tensor Shapes

In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[     1005362880,    433791762176,               8],
        [            256, 138172293853736,               0]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [28]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [23]:
#Tensor DataTypes

In [24]:
#find data type
x.dtype

torch.int64

In [25]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
#using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [29]:
#Mathematical operations

In [30]:
#1.Scalar opearations

In [32]:
x=torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [33]:
#addition
x+2
#substarction
x-2
#multiplication
x*2
#division
x/2
#int division
(x * 100) // 3
#mod
((x * 100)//3)%2
#power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

In [34]:
#2.Element wise operation

In [35]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [36]:
#add
a+b

tensor([[0.9229, 1.3130, 0.7983],
        [1.6774, 0.9717, 1.1950]])

In [37]:
#sub
a-b

tensor([[-0.5661,  0.3346,  0.3132],
        [ 0.2767, -0.0837,  0.7007]])

In [38]:
#mul
a * b

tensor([[0.1328, 0.4030, 0.1348],
        [0.6842, 0.2343, 0.2343]])

In [39]:
#div
a / b

tensor([[0.2397, 1.6841, 2.2912],
        [1.3951, 0.8415, 3.8346]])

In [40]:
#power
a ** b

tensor([[0.2771, 0.9096, 0.8672],
        [0.9839, 0.6515, 0.9868]])

In [41]:
#mod
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [42]:
c = torch.tensor([1,-2,3,-4])

In [43]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [44]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [46]:
d=torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [47]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [48]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [49]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [50]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

In [54]:
#3.Reduction operation
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[9., 7., 5.],
        [9., 8., 9.]])

In [55]:
#sum
torch.sum(e)
#sum along columns
torch.sum(e,dim=0)
#sum along rows
torch.sum(e,dim=1)

tensor([21., 26.])

In [56]:
#mean
torch.mean(e)

tensor(7.8333)

In [57]:
#mean along col
torch.mean(e,dim=0)

tensor([9.0000, 7.5000, 7.0000])

In [58]:
#median
torch.median(e)

tensor(8.)

In [59]:
#max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [60]:
#product
torch.prod(e)

tensor(204120.)

In [61]:
#standard deviation
torch.std(e)

tensor(1.6021)

In [62]:
#variance
torch.var(e)

tensor(2.5667)

In [63]:
#argmax
torch.argmax(e)

tensor(0)

In [64]:
#argmin
torch.argmin(e)

tensor(2)

In [67]:
#4.Matrix Operations
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [68]:
print(f)
print(g)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3],
        [6, 1],
        [5, 5]])


In [69]:
#matrix multiplication
torch.matmul(f,g)

tensor([[120,  40],
        [125,  60]])

In [70]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [71]:
#transpose
torch.transpose(f,0,1)

tensor([[7, 6],
        [9, 7],
        [2, 7]])

In [72]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [73]:
h

tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])

In [74]:
#determinant
torch.det(h)

tensor(84.)

In [75]:
#inverse
torch.inverse(h)

tensor([[-0.1786,  0.1786, -0.1429],
        [ 0.1071, -0.1071,  0.2857],
        [ 0.1905,  0.1429, -0.3810]])

In [76]:
#5.Comparison operations

In [77]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

In [78]:
print(i)
print(j)

tensor([[6, 4, 0],
        [8, 4, 7]])
tensor([[2, 3, 8],
        [5, 6, 2]])


In [84]:
#greater than
i>j

tensor([[ True,  True, False],
        [ True, False,  True]])

In [85]:
#less than
i<j

tensor([[False, False,  True],
        [False,  True, False]])

In [86]:
#equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [87]:
#not equal to
i!=j

tensor([[True, True, True],
        [True, True, True]])

In [88]:
#greater than equal to
i>=j

tensor([[ True,  True, False],
        [ True, False,  True]])

In [89]:
#6.Special functions

In [99]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[1., 1., 5.],
        [4., 4., 1.]])

In [100]:
#log
torch.log(k)

tensor([[0.0000, 0.0000, 1.6094],
        [1.3863, 1.3863, 0.0000]])

In [101]:
#exp
torch.exp(k)

tensor([[  2.7183,   2.7183, 148.4132],
        [ 54.5981,  54.5981,   2.7183]])

In [102]:
#sqrt
torch.sqrt(k)

tensor([[1.0000, 1.0000, 2.2361],
        [2.0000, 2.0000, 1.0000]])

In [103]:
#sigmoid
torch.sigmoid(k)

tensor([[0.7311, 0.7311, 0.9933],
        [0.9820, 0.9820, 0.7311]])

In [104]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.0474, 0.0474, 0.9820],
        [0.9526, 0.9526, 0.0180]])

In [105]:
#Inplace operations

In [106]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.3011, 0.1893, 0.9186],
        [0.2131, 0.3957, 0.6017]])
tensor([[0.4234, 0.5224, 0.4175],
        [0.0340, 0.9157, 0.3079]])


In [107]:
m+ n

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [108]:
m.add_(n)

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [109]:
m

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [110]:
torch.relu(m)

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [111]:
m.relu_()

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [112]:
m

tensor([[0.7245, 0.7117, 1.3361],
        [0.2472, 1.3114, 0.9096]])

In [113]:
#Copying a Tensor

In [115]:
a=torch.rand(2,3)
a

tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [116]:
b = a

In [117]:
a[0][0]=0

In [118]:
a

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [119]:
b

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [120]:
id(a)

138167468734768

In [121]:
id(b)

138167468734768

In [122]:
b = a.clone()

In [123]:
a

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [124]:
b

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [125]:
a[0][0]=10

In [126]:
a

tensor([[10.0000,  0.8497,  0.9112],
        [ 0.4847,  0.9436,  0.3904]])

In [127]:
b

tensor([[0.0000, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])

In [129]:
id(a)

138167468734768

In [131]:
id(b)

138167469098560

In [132]:
#Tensor Operations on GPU

In [133]:
torch.cuda.is_available()

True

In [134]:
device=torch.device('cuda')

In [135]:
#creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [137]:
#moving an existing tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])

In [139]:
b=a.to(device)
b

tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]], device='cuda:0')

In [140]:
b+5

tensor([[5.2336, 5.5057, 5.5688],
        [5.0634, 5.8993, 5.2732]], device='cuda:0')

In [144]:
import time

#Define the size of the metrices
size=10000 #Large size for performance comparison

#Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

#Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)  #Matrix multiplication on CPU
cpu_time=time.time()- start_time
print(f"Time on CPU:{cpu_time:.4f}seconds")

#Move matrices to GPU
matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')

#Measure time on GPU
start_time = time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2) #Matrix multiplication on GPU
torch.cuda.synchronize() #Ensure all GPU operations are complete
gpu_time=time.time()-start_time
print(f"Time on GPU:{gpu_time:.4f}seconds")

#Compare results
print("\nSppedup (CPU time / GPU time):",cpu_time / gpu_time)

Time on CPU:16.1404seconds
Time on GPU:0.5507seconds

Sppedup (CPU time / GPU time): 29.311221836731956


In [145]:
#Reshaping Tensors

In [146]:
a=torch.ones(4,4)

In [147]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [148]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [149]:
b=torch.rand(2,3,4)
b

tensor([[[0.6987, 0.7903, 0.5187, 0.7766],
         [0.9718, 0.5460, 0.9329, 0.9847],
         [0.6817, 0.2420, 0.6212, 0.0121]],

        [[0.0662, 0.3254, 0.6391, 0.1906],
         [0.6926, 0.0684, 0.8257, 0.4575],
         [0.6158, 0.6166, 0.1433, 0.7931]]])

In [150]:
#permute
b.permute(2,0,1)

tensor([[[0.6987, 0.9718, 0.6817],
         [0.0662, 0.6926, 0.6158]],

        [[0.7903, 0.5460, 0.2420],
         [0.3254, 0.0684, 0.6166]],

        [[0.5187, 0.9329, 0.6212],
         [0.6391, 0.8257, 0.1433]],

        [[0.7766, 0.9847, 0.0121],
         [0.1906, 0.4575, 0.7931]]])

In [152]:
#unsqueeze
c=torch.rand(226,226,3)
c

tensor([[[0.3980, 0.0345, 0.6398],
         [0.0010, 0.7428, 0.6992],
         [0.9302, 0.5812, 0.0991],
         ...,
         [0.1740, 0.5649, 0.5944],
         [0.2490, 0.5357, 0.8710],
         [0.0260, 0.5497, 0.7901]],

        [[0.6415, 0.9560, 0.5110],
         [0.8162, 0.4717, 0.0511],
         [0.1558, 0.8017, 0.0613],
         ...,
         [0.7635, 0.2318, 0.0188],
         [0.1218, 0.0245, 0.3634],
         [0.7191, 0.5467, 0.2790]],

        [[0.0185, 0.7829, 0.7450],
         [0.6622, 0.8849, 0.0900],
         [0.9555, 0.9725, 0.4041],
         ...,
         [0.2282, 0.1058, 0.9738],
         [0.5941, 0.3064, 0.7395],
         [0.7763, 0.6567, 0.8903]],

        ...,

        [[0.2871, 0.2023, 0.6058],
         [0.7130, 0.7383, 0.1033],
         [0.9359, 0.3503, 0.2592],
         ...,
         [0.9850, 0.2319, 0.2012],
         [0.1863, 0.3108, 0.7465],
         [0.5802, 0.2832, 0.7996]],

        [[0.7353, 0.5000, 0.4726],
         [0.6693, 0.3787, 0.8603],
         [0.

In [153]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [154]:
#squeeze
d=torch.rand(1,20)
d

tensor([[0.3665, 0.4654, 0.4611, 0.1430, 0.4602, 0.1254, 0.9687, 0.0025, 0.4223,
         0.8678, 0.8185, 0.9248, 0.3509, 0.2865, 0.3828, 0.3585, 0.7133, 0.9839,
         0.3870, 0.5860]])

In [155]:
#Numpy and PyTorch

In [156]:
import numpy as np

In [157]:
a=torch.tensor([1,2,3])

In [158]:
a

tensor([1, 2, 3])

In [159]:
b=a.numpy()

In [160]:
b

array([1, 2, 3])

In [161]:
type(b)

numpy.ndarray

In [162]:
c=np.array([1,2,3])

In [163]:
c

array([1, 2, 3])

In [164]:
torch.from_numpy(c)

tensor([1, 2, 3])